// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_tOK8GdEO6ETAyEHAFBNA228N_T2Vr8A',
    appId: '1:1031742263589:web:778bb46cd761bf7328cacc',
    messagingSenderId: '1031742263589',
    projectId: 'user-management-83c12',
    authDomain: 'user-management-83c12.firebaseapp.com',
    storageBucket: 'user-management-83c12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0PST2v7ztxjAOX3I9sS6YLdu1m6fH-SE',
    appId: '1:1031742263589:android:0b9730166398f75828cacc',
    messagingSenderId: '1031742263589',
    projectId: 'user-management-83c12',
    storageBucket: 'user-management-83c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOVOaaAT6nYcRIjHHL-0zxue2-kf33obk',
    appId: '1:1031742263589:ios:7120ce0fed0673a028cacc',
    messagingSenderId: '1031742263589',
    projectId: 'user-management-83c12',
    storageBucket: 'user-management-83c12.appspot.com',
    iosClientId: '1031742263589-h64e9g7egck0csc2bhmq7pic4re4jns5.apps.googleusercontent.com',
    iosBundleId: 'com.example.userManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOVOaaAT6nYcRIjHHL-0zxue2-kf33obk',
    appId: '1:1031742263589:ios:7120ce0fed0673a028cacc',
    messagingSenderId: '1031742263589',
    projectId: 'user-management-83c12',
    storageBucket: 'user-management-83c12.appspot.com',
    iosClientId: '1031742263589-h64e9g7egck0csc2bhmq7pic4re4jns5.apps.googleusercontent.com',
    iosBundleId: 'com.example.userManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_tOK8GdEO6ETAyEHAFBNA228N_T2Vr8A',
    appId: '1:1031742263589:web:b4aa10f96f5b035b28cacc',
    messagingSenderId: '1031742263589',
    projectId: 'user-management-83c12',
    authDomain: 'user-management-83c12.firebaseapp.com',
    storageBucket: 'user-management-83c12.appspot.com',
  );
}
